version: '3.8'

services:

  postgisdb:
    hostname: postgisdb
    build:
      context: ./docker/postgisdb
    
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports: 
      - "5499:5432"
    volumes:
      - db-data:/var/lib/postgrespers
    networks:
      - mvt-map-network

  mvt:
    build:
      context: ./docker/mvt
    environment:
      - MAPBOX_TOKEN=${MAPBOX_TOKEN}
    ports:
      - 5000:5000
    depends_on:
      - postgisdb

volumes:
  db-data:

networks:
  mvt-map-network: